export const TICKER_NAMES = {
  SPY:"S&P 500 ETF — 500 largest US companies", QQQ:"Nasdaq-100 ETF — top 100 tech stocks",
  IWM:"Russell 2000 ETF — 2000 small US companies", VTI:"Vanguard Total US Stock Market ETF",
  DIA:"Dow Jones ETF — 30 blue-chip companies", RSP:"Equal-Weight S&P 500 ETF",
  XLK:"Technology Sector ETF", XLE:"Energy Sector ETF", XLF:"Financial Sector ETF — banks, insurance",
  XLV:"Healthcare Sector ETF", XLY:"Consumer Discretionary ETF — Amazon, Tesla, Nike",
  XLP:"Consumer Staples ETF — Walmart, P&G, Coca-Cola", XLRE:"Real Estate Sector ETF",
  XLB:"Materials Sector ETF — chemicals, metals", XLI:"Industrials Sector ETF — Boeing, Caterpillar",
  XLU:"Utilities Sector ETF — electricity, water, gas",
  EFA:"International Developed Markets ETF", EEM:"Emerging Markets ETF — China, India, Brazil",
  VEA:"Vanguard Developed Markets ETF", VWO:"Vanguard Emerging Markets ETF",
  EWJ:"Japan ETF — Nikkei", FXI:"China Large-Cap ETF",
  TLT:"20+ Year US Treasury Bond ETF", AGG:"US Total Bond Market ETF",
  HYG:"High-Yield Corporate Bond ETF", LQD:"Investment-Grade Corporate Bond ETF",
  BND:"Vanguard Total Bond Market ETF", SHY:"1-3 Year Treasury Bond ETF — short-term, very safe",
  GLD:"Gold ETF — tracks gold price", SLV:"Silver ETF", IAU:"iShares Gold ETF",
  USO:"Crude Oil Fund — tracks US oil price", DBA:"Agriculture ETF — corn, soybeans, wheat",
  AAPL:"Apple Inc — iPhones, Macs, App Store, Services",
  MSFT:"Microsoft — Windows, Azure cloud, Office, LinkedIn",
  NVDA:"NVIDIA — AI chips (GPUs), data centres, gaming",
  GOOGL:"Alphabet — Google Search, YouTube, Google Cloud",
  META:"Meta Platforms — Facebook, Instagram, WhatsApp",
  AMZN:"Amazon — e-commerce, AWS cloud, Prime",
  TSLA:"Tesla — electric vehicles, energy storage, self-driving",
  "BRK-B":"Berkshire Hathaway — Warren Buffett's holding company",
  JPM:"JPMorgan Chase — largest US bank",
  V:"Visa Inc — global payment network",
  UNH:"UnitedHealth Group — largest US health insurer",
  LLY:"Eli Lilly — pharmaceuticals, Ozempic weight-loss drugs",
  AVGO:"Broadcom — semiconductors, networking chips",
  AMD:"Advanced Micro Devices — CPUs and GPUs, AI chip competitor",
  PLTR:"Palantir Technologies — AI/data analytics for governments",
  SNOW:"Snowflake — cloud data platform, AI analytics",
  CRWD:"CrowdStrike — cybersecurity, endpoint protection",
  NET:"Cloudflare — internet security, CDN, Zero Trust",
  DDOG:"Datadog — cloud monitoring platform",
  SMCI:"Super Micro Computer — AI server hardware",
  ARM:"Arm Holdings — chip architecture in almost every smartphone",
  QCOM:"Qualcomm — smartphone chips, 5G modems",
  MU:"Micron Technology — memory chips (DRAM, NAND)",
  INTC:"Intel Corp — CPUs, chip foundry (turnaround story)",
  AI:"C3.ai — enterprise AI applications",
  MELI:"MercadoLibre — Latin America's largest e-commerce",
  SE:"Sea Limited — Southeast Asia gaming and e-commerce",
  NVO:"Novo Nordisk — Ozempic/Wegovy weight-loss drugs",
  TSM:"Taiwan Semiconductor — world's largest chip maker",
  ASML:"ASML Holding — only maker of extreme UV chip machines",
  SHOP:"Shopify — e-commerce platform for businesses",
  ABNB:"Airbnb — home-sharing and travel platform",
  UBER:"Uber — ride-sharing and food delivery",
  CELH:"Celsius Holdings — fast-growing energy drink brand",
  ENPH:"Enphase Energy — solar microinverters",
  FSLR:"First Solar — US solar panel manufacturer",
  COIN:"Coinbase — largest US cryptocurrency exchange",
  RBLX:"Roblox — online gaming platform",
  IONQ:"IonQ — quantum computing company",
  UPST:"Upstart Holdings — AI-powered lending",
  SQ:"Block Inc (Square) — payments, Cash App, Bitcoin",
  PYPL:"PayPal — digital payments, Venmo",
  SOFI:"SoFi Technologies — digital financial services",
  AFRM:"Affirm Holdings — buy-now-pay-later platform",
  SOUN:"SoundHound AI — voice AI platform",
  RGTI:"Rigetti Computing — quantum computing",
  BBAI:"BigBear.ai — AI analytics for defense",
  GS:"Goldman Sachs — investment banking, trading",
  BAC:"Bank of America — second-largest US bank",
  XOM:"ExxonMobil — world's largest public oil company",
  CVX:"Chevron — integrated oil and gas",
  PFE:"Pfizer — pharmaceuticals, COVID vaccine maker",
  MRNA:"Moderna — mRNA vaccines and therapeutics",
  LYFT:"Lyft — ride-sharing platform",
  SPOT:"Spotify — music and podcast streaming",
  HOOD:"Robinhood — commission-free trading app",
  PTON:"Peloton Interactive — connected fitness equipment",
  ZM:"Zoom Video — video conferencing platform",
  // ETFs — expanded
  VOO:"Vanguard S&P 500 ETF", VTV:"Vanguard Value ETF", VUG:"Vanguard Growth ETF",
  MDY:"S&P MidCap 400 ETF", IJR:"iShares S&P Small-Cap 600 ETF", IVV:"iShares S&P 500 ETF",
  SCHB:"Schwab US Broad Market ETF", ITOT:"iShares Total US Stock Market ETF", SCHA:"Schwab US Small-Cap ETF",
  XLC:"Communication Services Sector ETF", XBI:"S&P Biotech ETF", IBB:"Nasdaq Biotech ETF",
  KRE:"Regional Banking ETF", ITB:"US Home Construction ETF", XHB:"S&P Homebuilders ETF",
  XRT:"Retail Sector ETF", XME:"Metals & Mining ETF",
  EWZ:"Brazil ETF", EWY:"South Korea ETF", EWG:"Germany ETF", EWU:"United Kingdom ETF",
  EWC:"Canada ETF", EWA:"Australia ETF", INDA:"India ETF", KWEB:"China Internet ETF",
  IEF:"7-10 Year Treasury ETF", VCIT:"Vanguard Intermediate Corp Bond ETF",
  VCSH:"Vanguard Short-Term Corp Bond ETF", MUB:"Municipal Bond ETF",
  TIP:"Inflation-Protected Securities ETF", GOVT:"US Government Bond ETF",
  EMB:"Emerging Markets Bond ETF", JNK:"SPDR High-Yield Bond ETF",
  PDBC:"Invesco DB Commodity ETF", CPER:"Copper ETF", UNG:"US Natural Gas Fund",
  WEAT:"Teucrium Wheat ETF", CORN:"Teucrium Corn ETF", SOYB:"Teucrium Soybean ETF", DBB:"Base Metals ETF",
  VNQ:"Vanguard Real Estate ETF",
  // Mega-cap additions
  GOOG:"Alphabet Class C shares", MA:"Mastercard — global payment network",
  HD:"Home Depot — largest US home improvement retailer", PG:"Procter & Gamble — consumer goods giant",
  JNJ:"Johnson & Johnson — pharma and medical devices", MRK:"Merck — vaccines and oncology drugs",
  // AI & Cloud additions
  ORCL:"Oracle — cloud database and enterprise software", ANET:"Arista Networks — cloud networking",
  MRVL:"Marvell Technology — data centre chips", CDNS:"Cadence — chip design software",
  SNPS:"Synopsys — chip design software",
  // Semiconductor additions
  LRCX:"Lam Research — chip equipment maker", AMAT:"Applied Materials — semiconductor equipment",
  KLAC:"KLA Corp — chip inspection equipment", ON:"ON Semiconductor — power chips",
  SWKS:"Skyworks — RF chips for smartphones", MCHP:"Microchip Technology — microcontrollers",
  ADI:"Analog Devices — analog and mixed-signal chips", TXN:"Texas Instruments — analog chips",
  NXPI:"NXP Semiconductors — auto and IoT chips", CRUS:"Cirrus Logic — audio chips for Apple",
  SITM:"SiTime — MEMS timing semiconductors", WOLF:"Wolfspeed — silicon carbide power chips",
  FORM:"FormFactor — chip testing equipment", COHU:"Cohu — semiconductor test equipment",
  ACLS:"Axcelis Technologies — ion implant systems",
  // Banks
  WFC:"Wells Fargo — third largest US bank", MS:"Morgan Stanley — investment banking and wealth",
  C:"Citigroup — global consumer and institutional bank", USB:"US Bancorp — regional bank",
  TFC:"Truist Financial — regional bank", PNC:"PNC Financial Services — regional bank",
  BK:"Bank of New York Mellon — custody bank", STT:"State Street — institutional asset manager",
  SCHW:"Charles Schwab — discount brokerage and banking", AXP:"American Express — premium credit cards",
  COF:"Capital One — credit cards and banking", DFS:"Discover Financial — credit cards",
  SYF:"Synchrony Financial — retail credit cards", ALLY:"Ally Financial — digital auto lending",
  RF:"Regions Financial — southeastern US bank", KEY:"KeyCorp — regional bank",
  HBAN:"Huntington Bancshares — midwest regional bank",
  // Healthcare additions
  ABBV:"AbbVie — Humira, Skyrizi, Rinvoq immunology drugs", BMY:"Bristol-Myers Squibb — oncology drugs",
  AMGN:"Amgen — biologics and biosimilars", GILD:"Gilead Sciences — HIV and liver drugs",
  REGN:"Regeneron — Eylea, Dupixent drugs", VRTX:"Vertex Pharmaceuticals — cystic fibrosis",
  BSX:"Boston Scientific — medical devices", MDT:"Medtronic — medical devices",
  SYK:"Stryker — orthopedic implants and surgical equipment",
  ZTS:"Zoetis — animal health medicines", DXCM:"DexCom — continuous glucose monitors",
  ISRG:"Intuitive Surgical — da Vinci robotic surgery", HCA:"HCA Healthcare — hospital operator",
  CI:"Cigna — health insurance", CVS:"CVS Health — pharmacy and insurance",
  MRNA:"Moderna — mRNA vaccines", BIIB:"Biogen — neurology drugs",
  // Energy additions
  COP:"ConocoPhillips — independent oil and gas", EOG:"EOG Resources — shale oil producer",
  SLB:"SLB (Schlumberger) — oilfield services giant", PSX:"Phillips 66 — refining and chemicals",
  VLO:"Valero Energy — largest US refiner", MPC:"Marathon Petroleum — refining",
  OXY:"Occidental Petroleum — oil and chemicals", DVN:"Devon Energy — shale oil",
  HAL:"Halliburton — oilfield services", BKR:"Baker Hughes — oilfield equipment",
  MRO:"Marathon Oil — exploration and production", APA:"APA Corp — global oil and gas",
  EQT:"EQT Corp — largest US natural gas producer", AR:"Antero Resources — natural gas",
  CHK:"Chesapeake Energy — natural gas", FANG:"Diamondback Energy — Permian Basin oil",
  CTRA:"Coterra Energy — natural gas and oil", SM:"SM Energy — oil and gas",
  // Consumer additions
  MCD:"McDonald's — global fast food chain", NKE:"Nike — global athletic footwear and apparel",
  SBUX:"Starbucks — global coffee chain", TGT:"Target — US mass retailer",
  WMT:"Walmart — world's largest retailer", COST:"Costco — warehouse club retailer",
  LOW:"Lowe's — home improvement retailer", TJX:"TJ Maxx parent — off-price retailer",
  BKNG:"Booking Holdings — Booking.com, Priceline, Kayak",
  MAR:"Marriott International — largest hotel chain", HLT:"Hilton — global hotel chain",
  CMG:"Chipotle Mexican Grill — fast casual restaurant",
  CVNA:"Carvana — online used car dealer", ETSY:"Etsy — handmade goods marketplace",
  EBAY:"eBay — online auction and shopping", DASH:"DoorDash — food delivery platform",
  DPZ:"Domino's Pizza — global pizza delivery", YUM:"Yum! Brands — KFC, Taco Bell, Pizza Hut",
  // Fintech
  FIS:"Fidelity National Info Services — payment processing",
  FISV:"Fiserv — financial technology", GPN:"Global Payments — payment processing",
  BILL:"Bill.com — SMB payments automation", DKNG:"DraftKings — sports betting platform",
  // Growth additions
  ZS:"Zscaler — cloud security platform", PANW:"Palo Alto Networks — cybersecurity",
  OKTA:"Okta — identity and access management", MNDY:"Monday.com — work OS platform",
  GTLB:"GitLab — DevOps platform", SHOP:"Shopify — e-commerce platform",
  COIN:"Coinbase — largest US crypto exchange", RBLX:"Roblox — online gaming platform",
  // Value additions
  T:"AT&T — US telecom giant", VZ:"Verizon — US wireless carrier",
  KO:"Coca-Cola — global beverage giant", PEP:"PepsiCo — beverages and snacks",
  PM:"Philip Morris — tobacco (now smoke-free products)", MO:"Altria — US tobacco",
  MMM:"3M — industrial and consumer products", GE:"GE Aerospace — jet engines",
  HON:"Honeywell — industrial automation and aerospace", CAT:"Caterpillar — construction equipment",
  DE:"Deere & Company — farm and construction equipment",
  EMR:"Emerson Electric — industrial automation", ETN:"Eaton — power management",
  ITW:"Illinois Tool Works — industrial products",
  // Emerging Markets
  BABA:"Alibaba — China's largest e-commerce", PDD:"PDD Holdings — Pinduoduo, Temu",
  JD:"JD.com — China's second-largest e-commerce", BIDU:"Baidu — China's Google",
  NIO:"NIO — Chinese electric vehicle maker", LI:"Li Auto — Chinese hybrid EV maker",
  XPEV:"XPeng — Chinese electric vehicle maker", GRAB:"Grab — Southeast Asia super app",
  GLOB:"Globant — Latin America IT services", VALE:"Vale — Brazil iron ore and nickel",
  ITUB:"Itaú Unibanco — Brazil's largest private bank",
  HDB:"HDFC Bank — India's largest private bank", IBN:"ICICI Bank — major Indian bank",
  INFY:"Infosys — India IT services giant",
  // REITs
  O:"Realty Income — monthly dividend REIT", SPG:"Simon Property — largest US mall REIT",
  AMT:"American Tower — cell tower REIT", PLD:"Prologis — logistics warehouse REIT",
  CCI:"Crown Castle — cell tower and fiber REIT", EQIX:"Equinix — data centre REIT",
  PSA:"Public Storage — self-storage REIT", DLR:"Digital Realty — data centre REIT",
  WELL:"Welltower — senior housing REIT", AVB:"AvalonBay — apartment REIT",
  EQR:"Equity Residential — apartment REIT", MAA:"Mid-America Apartment — sunbelt REIT",
  NNN:"NNN REIT — net lease retail", WPC:"W. P. Carey — diversified net lease REIT",
  STAG:"STAG Industrial — industrial REIT", REXR:"Rexford Industrial — SoCal warehouses",
  EXR:"Extra Space Storage — self-storage REIT",
  // Dividend additions
  GD:"General Dynamics — defense contractor", LMT:"Lockheed Martin — largest defense contractor",
  RTX:"RTX Corp — Raytheon, Pratt & Whitney", ABT:"Abbott Laboratories — medical devices and nutrition",
  // Tech Giants additions
  CRM:"Salesforce — cloud CRM platform", ADBE:"Adobe — creative and document cloud",
  NOW:"ServiceNow — enterprise workflow platform", IBM:"IBM — hybrid cloud and AI",
  CSCO:"Cisco — networking equipment and software", DELL:"Dell Technologies — PCs and servers",
  HPE:"Hewlett Packard Enterprise — servers and storage",
  // Small-cap additions
  DUOL:"Duolingo — language learning app", CROX:"Crocs — footwear brand",
  RELY:"Remitly Global — digital remittances", NU:"Nu Holdings — Brazilian digital bank",
}

export const UNIVERSE = {
  "US Broad":       ["SPY","QQQ","IWM","VTI","DIA","RSP","VOO","VTV","VUG","MDY","IJR","IVV","SCHB","ITOT","SCHA"],
  "Sectors":        ["XLK","XLE","XLF","XLV","XLY","XLP","XLRE","XLB","XLI","XLU","XLC","XBI","IBB","KRE","ITB","XHB","XRT","XME"],
  "Global":         ["EFA","EEM","VEA","VWO","EWJ","FXI","EWZ","EWY","EWG","EWU","EWC","EWA","INDA","KWEB"],
  "Bonds":          ["TLT","AGG","HYG","LQD","BND","SHY","IEF","VCIT","VCSH","MUB","TIP","GOVT","EMB","JNK"],
  "Commodities":    ["GLD","SLV","IAU","USO","DBA","PDBC","CPER","UNG","WEAT","CORN","SOYB","DBB"],
  "Mega-Cap":       ["AAPL","MSFT","NVDA","GOOGL","GOOG","META","AMZN","TSLA","BRK-B","JPM","V","UNH","LLY","AVGO","XOM","MA","HD","PG","JNJ","MRK"],
  "AI & Cloud":     ["NVDA","AMD","PLTR","SNOW","CRWD","NET","DDOG","SMCI","ARM","QCOM","MU","AI","MSFT","GOOGL","ORCL","ANET","MRVL","TSM","AVGO","CDNS","SNPS"],
  "Semiconductors": ["NVDA","AMD","QCOM","MU","INTC","AVGO","TSM","ASML","LRCX","AMAT","KLAC","MRVL","ON","SWKS","MCHP","ADI","TXN","NXPI","CRUS","SITM"],
  "Banks":          ["JPM","BAC","WFC","GS","MS","C","USB","TFC","PNC","BK","STT","SCHW","AXP","COF","DFS","SYF","ALLY","RF","KEY","HBAN"],
  "Healthcare":     ["UNH","LLY","JNJ","MRK","ABBV","BMY","PFE","AMGN","GILD","REGN","VRTX","BSX","MDT","SYK","ZTS","DXCM","ISRG","HCA","CI","CVS","MRNA","BIIB"],
  "Energy":         ["XOM","CVX","COP","EOG","SLB","PSX","VLO","MPC","OXY","DVN","HAL","BKR","MRO","APA","EQT","AR","CHK","FANG","CTRA","SM"],
  "Consumer":       ["AMZN","TSLA","HD","MCD","NKE","SBUX","TGT","WMT","COST","LOW","TJX","BKNG","MAR","HLT","CMG","UBER","ABNB","CVNA","ETSY","EBAY","DASH","DPZ","YUM"],
  "Fintech":        ["V","MA","PYPL","SQ","COIN","HOOD","AFRM","SOFI","UPST","NU","FIS","FISV","GPN","BILL","DKNG"],
  "Growth":         ["CELH","ENPH","FSLR","RBLX","IONQ","UPST","SOFI","AFRM","SOUN","RGTI","PLTR","SNOW","NET","DDOG","ZS","PANW","OKTA","MNDY","GTLB","SHOP"],
  "Value":          ["BRK-B","JPM","BAC","GS","XOM","CVX","PFE","INTC","WFC","C","T","VZ","KO","PEP","PM","MO","ABBV","BMY","MRK","MMM","GE","HON","CAT","DE","EMR","ETN","ITW"],
  "Emerging Mkts":  ["MELI","SE","NVO","ASML","TSM","ARM","BABA","PDD","JD","BIDU","NIO","LI","XPEV","GRAB","GLOB","VALE","ITUB","HDB","IBN","INFY"],
  "Real Estate":    ["VNQ","O","SPG","AMT","PLD","CCI","EQIX","PSA","DLR","WELL","AVB","EQR","MAA","NNN","WPC","STAG","REXR","EXR"],
  "Dividend":       ["O","T","VZ","KO","PEP","JNJ","PG","MO","PM","MMM","EMR","XOM","CVX","CAT","DE","HON","ITW","GD","LMT","RTX","ABT","MDT","MCD","WMT","HD"],
  "Small-Cap":      ["HOOD","IONQ","RGTI","SOUN","BBAI","UPST","AFRM","SOFI","DKNG","CELH","ENPH","WOLF","FORM","COHU","ACLS","CROX","DUOL","BILL","RELY","NU"],
  "Tech Giants":    ["AAPL","MSFT","GOOGL","GOOG","META","AMZN","NVDA","TSLA","ORCL","CRM","ADBE","NOW","IBM","CSCO","ANET","DELL","HPE"],
}

export const GLOBAL_CHAINS = [
  { region:"🇨🇳 China", event:"PMI / Stimulus / Trade", proxy:"FXI",
    proxyName:"China Large-Cap ETF — tracks biggest Chinese companies listed in HK",
    affects:["FXI","EEM","GLD","USO","AAPL","TSLA"], color:"#FF6B6B",
    why:"China is the world's largest commodity consumer. Weak PMI = lower global growth expectations. Strong stimulus = commodity rally, EM boost. US tech companies with heavy China revenue (Apple, Tesla) are directly exposed." },
  { region:"🇪🇺 Europe", event:"ECB Rate Decision", proxy:"EFA",
    proxyName:"International Developed Markets ETF — Europe, Japan, Australia stocks",
    affects:["EFA","VEA","TLT","JPM"], color:"#4ECDC4",
    why:"ECB cutting faster than Fed strengthens the US Dollar — headwind for US multinationals earning in euros. European economic weakness exports deflation globally." },
  { region:"🇯🇵 Japan", event:"BOJ / Yen Carry Trade", proxy:"EWJ",
    proxyName:"Japan ETF — tracks the Japanese stock market (Nikkei)",
    affects:["EWJ","SPY","QQQ","TLT"], color:"#A78BFA",
    why:"Traders borrow cheap yen, buy US assets (carry trade). When BOJ raises rates → yen strengthens → forced unwinding → US stocks sell off. A Nikkei crash shows up as S&P 500 futures dropping pre-market." },
  { region:"🛢 Oil", event:"OPEC / Supply Shock", proxy:"USO",
    proxyName:"US Oil Fund — tracks the price of crude oil futures",
    affects:["USO","XLE","SPY","XLY"], color:"#F59E0B",
    why:"Oil affects inflation expectations, consumer spending, and Fed policy. A $10 oil spike = ~0.4% CPI impact. Energy stocks benefit; consumer discretionary stocks are hurt (higher fuel costs = less spending)." },
  { region:"🥇 Gold", event:"Risk-Off / Geopolitics", proxy:"GLD",
    proxyName:"Gold ETF — tracks the price of physical gold",
    affects:["GLD","SLV","IAU","TLT"], color:"#FFD700",
    why:"Gold rising = market fear. Signals rotation out of equities into safe havens. If gold AND bonds both rise simultaneously, it's a genuine risk-off event, not just sector rotation." },
  { region:"💵 US Dollar", event:"DXY Strength / Fed Divergence", proxy:"SPY",
    proxyName:"S&P 500 ETF — best proxy for broad USD impact on US equities",
    affects:["EEM","GLD","USO","AAPL","MSFT","GOOGL"], color:"#00E5FF",
    why:"The S&P 500 earns ~40% of revenues abroad. A strong USD shrinks foreign earnings when converted back to dollars. Emerging market assets are particularly hurt — dollar-denominated debt becomes more expensive to service." },
  { region:"⚡ Semiconductors", event:"Taiwan / TSMC / Export Controls", proxy:"NVDA",
    proxyName:"NVIDIA Corp — world's leading AI chip designer",
    affects:["NVDA","AAPL","AMD","MSFT","XLK"], color:"#C084FC",
    why:"Taiwan produces ~90% of the world's advanced chips. Any geopolitical disruption = supply chain panic across all tech. TSMC risk hits Apple, NVIDIA, AMD, Microsoft simultaneously — no substitutes exist at scale." },
  { region:"🇮🇳 India", event:"Growth / Policy / Elections", proxy:"EEM",
    proxyName:"Emerging Markets ETF — India is its fastest-growing component",
    affects:["EEM","VWO","GOOGL","META"], color:"#F97316",
    why:"Fastest-growing major economy. Strong India data boosts EM sentiment broadly. US tech with large India operations (Google Cloud, Meta's ad business) benefit from India's expanding digital consumer base." },
]

export const MACRO = {
  regime: "Neutral · Consolidation · Tariff Uncertainty",
  summary: "Markets in consolidation after strong 2024 AI rally. Trump tariff policy creating cross-asset volatility — USD strengthening, EM under pressure. Fed on hold at 4.25–4.5%, no cuts priced until H2 2026. Inflation sticky at ~2.8%. Labour market solid at ~4.1%. AI capex supercycle intact but valuations stretched. Bond yields elevated — 10Y at ~4.3%.",
  tailwinds: [
    ["AI & Data Centres", "NVDA, AVGO, MSFT capex buildout continues — AI infrastructure demand structural, not cyclical."],
    ["Defence & Industrials", "NATO spending mandates + US defence budget expansion lifting LMT, RTX, GD, NOC."],
    ["Gold & Hard Assets", "Central bank buying + geopolitical uncertainty + de-dollarisation thesis pushing GLD, GDX higher."],
    ["Energy (Oil & Gas)", "Supply discipline from OPEC+ + geopolitical risk premium keeping XOM, CVX, COP resilient."],
  ],
  headwinds: [
    ["Tariff Risk", "US trade policy uncertainty hitting consumer goods, autos, and tech hardware supply chains."],
    ["High Valuations", "S&P forward P/E ~21x — above historical average. Any earnings miss punished hard."],
    ["Rates Staying Higher", "Fed on hold — no cuts until late 2026 at earliest. Pressure on long-duration assets and REITs."],
    ["China / EM Exposure", "Tariffs + strong USD = headwind for multinationals with significant China revenue (AAPL, QCOM)."],
  ],
}

export const EDUCATION = {
  "Getting Started": [
    { title:"What is the Stock Market?",
      body:"A marketplace where people buy and sell small pieces (shares) of companies. When you own a share of Apple, you own a tiny fraction of Apple Inc. If Apple becomes more valuable, your share is worth more.",
      links:[["Investopedia — Stock Market Basics","https://www.investopedia.com/terms/s/stockmarket.asp"],["Khan Academy — Stocks","https://www.khanacademy.org/economics-finance-domain/core-finance/stock-and-bonds"],["SEC — Investing Basics","https://www.investor.gov/introduction-investing/investing-basics"]] },
    { title:"ETFs — Instant Diversification",
      body:"An ETF (Exchange-Traded Fund) is a basket of stocks. SPY contains all 500 S&P 500 companies. One purchase = instant diversification. They trade on exchanges like individual stocks.",
      links:[["Investopedia — ETF Guide","https://www.investopedia.com/terms/e/etf.asp"],["Vanguard — What is an ETF?","https://investor.vanguard.com/investor-resources-education/etfs/what-is-an-etf"]] },
    { title:"How to Open a Brokerage Account",
      body:"Choose a broker (Fidelity, Schwab, or Robinhood — all commission-free). Deposit money via bank transfer. Search a ticker. Enter shares. Choose market or limit order. Confirm.",
      links:[["NerdWallet — Best Brokers","https://www.nerdwallet.com/best/investing/online-brokers-for-stock-trading"],["SEC — Getting Started","https://www.investor.gov/introduction-investing/getting-started"]] },
  ],
  "Charts & Technical": [
    { title:"Candlestick Charts",
      body:"Each candle = one day of trading. Green = price closed higher than opened. Red = closed lower. Thin wicks show the highest and lowest price of the day. PULSE uses these on all chart views.",
      links:[["Investopedia — Candlesticks","https://www.investopedia.com/articles/active-trading/092315/5-most-powerful-candlestick-patterns.asp"],["TradingView — Free Charts","https://www.tradingview.com"]] },
    { title:"Moving Averages",
      body:"Average of the last N closing prices. Price above 50-day MA = buyers in control. Below = weakness. Golden cross (50MA crosses above 200MA) = historically bullish.",
      links:[["Investopedia — Moving Averages","https://www.investopedia.com/terms/m/movingaverage.asp"]] },
    { title:"RSI — Relative Strength Index",
      body:"0-100 momentum gauge. Above 70 = overbought (pullback risk). Below 30 = oversold (bounce potential). 40-60 = neutral. Best used alongside trend analysis.",
      links:[["Investopedia — RSI","https://www.investopedia.com/terms/r/rsi.asp"]] },
  ],
  "Stock Analysis": [
    { title:"P/E Ratio",
      body:"Share price ÷ annual earnings per share. P/E 10-15 = value. P/E 20-30 = growth premium. P/E 40+ = expensive, must keep growing fast. S&P 500 average ~20×.",
      links:[["Investopedia — P/E Ratio","https://www.investopedia.com/terms/p/price-earningsratio.asp"]] },
    { title:"Earnings Beats",
      body:"Each quarter companies report actual EPS vs analyst estimates. Beat = stock often rises. Miss = often falls 10-20%. Beat rate over 4 quarters signals reliable management.",
      links:[["Earnings Whispers","https://www.earningswhispers.com"],["Investopedia — EPS","https://www.investopedia.com/terms/e/eps.asp"]] },
    { title:"Insider Transactions",
      body:"When executives buy company stock with own money = confidence signal. Cluster buying by multiple insiders same week = strongest signal. Filed with SEC within 2 days (Form 4).",
      links:[["OpenInsider","http://openinsider.com"],["SEC EDGAR","https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&type=4"]] },
  ],
  "Options Trading": [
    { title:"What is an Options Contract?",
      body:"An option gives you the RIGHT (not obligation) to buy or sell 100 shares at a fixed price (strike) before expiry. Max loss as a buyer = the premium you paid. One contract = 100 shares.",
      links:[["Investopedia — Options Basics","https://www.investopedia.com/options-basics-tutorial-4583012"],["CBOE — Options Education","https://www.cboe.com/education/"]] },
    { title:"Calls vs Puts",
      body:"CALL = right to BUY 100 shares. Profit when stock rises above strike + premium. PUT = right to SELL 100 shares. Profit when stock falls. Puts also used as insurance/hedges.",
      links:[["Investopedia — Call vs Put","https://www.investopedia.com/ask/answers/difference-between-put-and-call-option/"]] },
    { title:"The Greeks — IV, Theta, Delta",
      body:"Delta: how much option price moves per $1 stock move. Theta: daily time decay — accelerates near expiry. IV: how much volatility is priced in. High IV = expensive options. Buy when IV is low.",
      links:[["Investopedia — Options Greeks","https://www.investopedia.com/trading/getting-to-know-the-greeks/"],["CBOE VIX","https://www.cboe.com/tradable_products/vix/"]] },
    { title:"Covered Call — Income Strategy",
      body:"Sell a call on shares you already own. Collect premium immediately. If stock stays below strike by expiry = keep shares AND premium. Best in flat/slow-rising markets.",
      links:[["Investopedia — Covered Call","https://www.investopedia.com/terms/c/coveredcall.asp"]] },
  ],
  "Risk Management": [
    { title:"Position Sizing",
      body:"Never put more than 5-10% of portfolio in a single stock. With $10,000: max $500-1,000 per name. Even a total bankruptcy loses you only 5-10% of total wealth.",
      links:[["Investopedia — Position Sizing","https://www.investopedia.com/terms/p/positionsizing.asp"]] },
    { title:"Dollar-Cost Averaging (DCA)",
      body:"Instead of investing $10,000 all at once, invest $1,000/month for 10 months. You buy at different price levels. Average cost smooths out volatility. Use the DCA Calculator below.",
      links:[["Investopedia — DCA","https://www.investopedia.com/terms/d/dollarcostaveraging.asp"]] },
    { title:"Free Research Tools",
      body:"Best free tools: Yahoo Finance for quotes, Finviz for screening, FRED for economic data, OpenInsider for insider buying, SEC EDGAR for primary filings.",
      links:[["Finviz","https://finviz.com"],["FRED Economic Data","https://fred.stlouisfed.org"],["OpenInsider","http://openinsider.com"]] },
  ],
}

export const GLOSSARY = [
  ["P/E Ratio","How much you pay per $1 of profit. P/E 20 = $20 paid per $1 earned. High = expensive. S&P 500 average ~20×."],
  ["EPS (Earnings Per Share)","Total company profit ÷ total shares. Growing EPS = business improving."],
  ["RSI (Relative Strength Index)","0–100 momentum gauge. Above 70 = overbought. Below 30 = oversold. 40-60 = neutral."],
  ["50-Day MA","Average closing price over last 50 trading days. Price above = uptrend. Below = weakness."],
  ["Beta","Volatility vs the market. Beta 1.5 = if market drops 10%, this drops ~15%."],
  ["8-K Filing","SEC form filed within 4 days of major company event. Best way to verify big news."],
  ["Form 4","Filed when corporate insiders buy or sell company stock within 2 days."],
  ["Conviction Score","How many of 6 factors agree. More agreeing = higher conviction."],
  ["Why Now vs Why At All","Great company ≠ great buy today. Why Now = timing. Why At All = business quality."],
  ["DXY (Dollar Index)","Measures USD against 6 major currencies. Rising DXY = strong dollar = headwind for US multinationals."],
  ["Carry Trade","Borrow in low-rate currency (JPY), invest higher-yield. When JPY strengthens, carry unwinds."],
  ["PMI","0-100 business survey. Above 50 = expansion. Below 50 = contraction."],
  ["Source Tier","T1=SEC/Fed, T2=Reuters/Bloomberg, T3=CNBC/Forbes, T4=anonymous. Higher tier = more weight."],
  ["Call Option","Right to BUY 100 shares at strike price. Max loss = premium paid."],
  ["Put Option","Right to SELL 100 shares at strike price. Profit when stock falls."],
  ["Strike Price","Fixed price in options contract. Stock must cross this for option to be profitable."],
  ["Premium","Price you pay to buy an option. $3 premium = $300 total cost = max loss."],
  ["Covered Call","Sell a call on shares you own. Collect premium. Works in flat/slow markets."],
  ["IV (Implied Volatility)","Market's expected future volatility in option prices. High IV = expensive options."],
  ["Theta (Time Decay)","Options lose value daily. Accelerates near expiry. Works against buyers."],
  ["Proxy","ETF/stock that best represents a region/event as a live price signal."],
  ["Market Cap","Total company value = price × shares. Large-cap >$10B. Small-cap <$2B."],
  ["DCA (Dollar-Cost Averaging)","Investing fixed amount regularly regardless of price. Removes emotional timing."],
  ["Golden Cross","50-day MA crosses above 200-day MA. Historically bullish signal."],
]

export const SOURCE_TIERS = {
  1: { sources:["SEC","EDGAR","Federal Reserve","Fed","FDIC","ECB","IMF","World Bank"], label:"Regulatory", color:"#00E5FF", weight:1.00 },
  2: { sources:["Reuters","Associated Press","Bloomberg","Dow Jones","AP","WSJ","Wall Street Journal","Financial Times","FT","MarketWatch","Nikkei"], label:"Major Wire", color:"#00C805", weight:0.85 },
  3: { sources:["CNBC","Forbes","Barrons","Seeking Alpha","Motley Fool","Yahoo Finance","Business Insider","Benzinga"], label:"Financial Media", color:"#FFD700", weight:0.60 },
  4: { label:"Unverified", color:"#FF5000", weight:0.30 },
}

export const OPTIONS_STRATEGIES = {
  BUY: {
    title:"BULLISH SETUPS", color:"#00C805",
    strategies:[
      { name:"Long Call", risk:"High", reward:"Unlimited",
        desc:"Buy a call 5-10% above current price. 30-45 DTE. Max loss = premium paid.",
        when:"IV below 30. Not the week before earnings — IV crush will destroy your premium.",
        exit:"Sell at 50-100% profit. Stop at 50% premium loss. Don't hold to expiry." },
      { name:"Bull Call Spread", risk:"Limited", reward:"Capped",
        desc:"Buy call at-the-money, sell call 10-15% higher. Reduces cost. Caps upside.",
        when:"When IV is elevated — spread benefits from high premium on the short leg.",
        exit:"Close at 50% of max profit. Rarely worth holding for the last 10%." },
      { name:"Covered Call (income)", risk:"Capped upside", reward:"Premium income",
        desc:"Sell a call 5-10% above price on shares you already own. Collect premium.",
        when:"Sideways or slow-rising market. Set strike above key resistance.",
        exit:"Let expire worthless. Or buy back at 80% profit to keep open the position." },
    ],
    warning:"Keep total options exposure below 10% of portfolio. Earnings = binary risk — avoid holding through unless intentional.",
  },
  HOLD: {
    title:"NEUTRAL / INCOME SETUPS", color:"#FFD700",
    strategies:[
      { name:"Iron Condor", risk:"Limited", reward:"Premium income",
        desc:"Sell call AND put outside expected range. Profit if stock stays in the range.",
        when:"IV is high (above 30). Stock consolidating. Ideal for earnings plays.",
        exit:"Close at 50% of max profit. Never hold to max loss." },
      { name:"Cash-Secured Put", risk:"Own shares at lower price", reward:"Premium income",
        desc:"Sell a put below current price. If stock falls to strike, you buy shares at that price.",
        when:"Stock you genuinely want to own at a lower price. Strong support below.",
        exit:"Let expire if above strike. Accept assignment if stock falls through." },
      { name:"Covered Call", risk:"Capped upside", reward:"Monthly income 1-2%",
        desc:"Sell calls against shares you hold. Neutral signal = ideal time to monetise sideways movement.",
        when:"Set strike above current resistance. 30-45 DTE.",
        exit:"Buy back at 80% profit or let expire." },
    ],
    warning:"Neutral signal = reduced directional exposure is correct. Focus on income strategies.",
  },
  AVOID: {
    title:"BEARISH / DEFENSIVE SETUPS", color:"#FF5000",
    strategies:[
      { name:"Long Put", risk:"Premium paid", reward:"High (stock falls)",
        desc:"Buy a put 5-10% below current price. 30-45 DTE. Profit as stock falls.",
        when:"IV is low. If IV elevated, use put spread instead.",
        exit:"Sell at 50-100% profit. Exit before positive catalysts." },
      { name:"Bear Put Spread", risk:"Limited", reward:"Capped",
        desc:"Buy put at-the-money, sell put 10-15% lower. Reduces cost significantly.",
        when:"IV is elevated — uses high premium in your favour on the short leg.",
        exit:"Close at 50% of max profit." },
      { name:"Reduce / Hedge", risk:"Opportunity cost", reward:"Capital preservation",
        desc:"AVOID = don't open new long positions. Consider protective puts on existing holdings.",
        when:"This is a defensive signal. Sit out or hedge.",
        exit:"N/A" },
    ],
    warning:"AVOID signal means the odds are not in your favour. Bears get killed by timing — don't short just because something looks expensive.",
  },
}
